export const RULES = {
    tickRate: 30,
    roundTimeSeconds: 1200,
    countdownTimeSeconds: 5,
    preliveTimeSeconds: 15,
    postmatchTimeSeconds: 20,
    redeployTimeSeconds: 10,
    objectiveInteractHoldSeconds: 3,
    gameplay: {
        initialTickets: 200,
        deathTicketLoss: -1,
        bleedPerSecond: {
            oneFlag: -0.33,
            twoFlags: -0.5,
            threeFlags: -1,
        },
        capture: {
            captureSeconds: 6,
            neutralizeSeconds: 6,
            twoPlayerMultiplier: 2,
            maxMultiplier: 1.6,
            progressEpsilon: 0.02,
        },
        safeSpawn: {
            checkDelaySeconds: 0.1,
            radiusStartMeters: 25,
            radiusEndMeters: 8,
            maxForcedRedeploys: 5,
            radiusReachEndUsed: 4,
            capturePointThreatRadius: {
                referenceDistanceMeters: 120,
                referenceRadiusMeters: 26,
                minMeters: 12,
                maxMeters: 32,
            },
            liveRouteRefreshSeconds: 0.25,
            liveRouteSwitchMarginMeters: 10,
            squadSpawnDistanceMeters: 8,
            squadProbeWindowSeconds: 0.25,
            squadProbeIntervalSeconds: 0.05,
            squadBypassLifetimeSeconds: 1,
            hqDesyncEpsilonMeters: 0.5,
            hqDesyncMaxForcedRedeploys: 2,
            hqDesyncCheckEnabled: true,
            friendlySpawnBypassMeters: 8,
            hqRoutingSafetyIntervalSeconds: 2,
            checkQueueBudgetPerTick: 2,
            forcedSpawnQueueBudgetPerTick: 1,
            forcedSpawnDelaySeconds: 0.2,
        },
        spatialHash: {
            cellSizeMeters: 32,
        },
        damage: {
            enableSmoothing: false,
            restrictedPulseDamage: 8,
            restrictedPulseIntervalSeconds: 0.25,
            smoothingSpread: {
                closeMaxDist: 10,
                midMaxDist: 25,
                closeSeconds: 2,
                midSeconds: 1.8,
                farSeconds: 1.6,
                minHealthDelayFactor: 0.45,
                maxHealthDelayFactor: 1,
            },
        },
    },
    timerLanes: {
        disabledMcomEnforceMs: 500,
        phaseSecondMs: 1000,
        liveFastMs: 100,
        liveSlowMs: 300,
        endgameAudioMs: 500,
        capturePointReconcileMs: 500,
        uiClockMs: 1000,
        damageZonePulseMs: 250,
        iconFollowMs: 50,
        holdUiMs: 50,
        noFireEnforceMs: 1000,
    },
    audio: {
        captureTickIntervalSeconds: 0.45,
        captureBuildupThreshold: 0.88,
        captureBuildupLeadSeconds: 0.45,
        captureBuildupBeats: 3,
        captureBuildupBeatIntervalSeconds: 0.12,
        captureBuildupCooldownSeconds: 2,
        captureBuildupProfile: 'captureLeadin',
        captureBuildupBeatVolumes: [0.18, 0.23, 0.3],
    },
    music: {
        enabled: true,
        package: 'Core',
        endgameTicketThreshold: 50,
        endgameTimeThresholdSeconds: 30,
        urgencyMin: 0,
        urgencyMax: 4,
        fallbackToSfxLoops: true,
    },
    debug: {
        parityDiagnostics: false,
        livePerformanceDiagnostics: false,
    },
} as const;
